### ISSUE TITLE
Unable to clone DyadInterface.jl

### ISSUE THREAD

**Issue by sibeov** [DyadLang/DyadIssues#12]
# Summary
Tried the `Gyad Studio` extensions "Create Component Library" 
Tried to do a `pkg> actiave .` and `pkg> test` which resulted in this error:
```shell
ERROR: failed to clone from https://github.com/JuliaComputing/DyadInterface.jl.git, error: GitError(Code:ERROR, Class:HTTP, unexpected http status code: 404)
```

# How to reproduce
1. Install Julia 1.11.5
2. Install Dyad Studio
3. Open VScode and execute the `Dyad: Create Component Library` function
4. Enter Terminal and enter Julia REPL 
5. Enter package mode
6. Execute `activate .`
7. Execute `test`

# Enviornment
Julia:  v1.11.5
OS: NixOS 25.05.20250613.5f4f306 (Warbler) x86_64
Kernel: 6.12.33

## Project.toml
This `Project.toml` file was generated:
```toml
name = "MyComponents"
uuid = "548fbddd-e0f1-4272-9e72-4245fb643b04"
version = "0.1.0"

[deps]
DyadEcosystemDependencies = "7bc808db-8006-421e-b546-062440d520b7"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
DyadInterface = "99806f68-afab-45ca-9d8c-ceff6bc61f54"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
OrdinaryDiffEqDefault = "50262376-6c5a-4cf5-baba-aaf4f84d72d7"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
RuntimeGeneratedFunctions = "7e49a35a-f44a-4d26-94aa-eba1b4ca6b47"

[compat]
DyadEcosystemDependencies = "=0.9.4"
Markdown = "1"

[extras]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["CSV","DataFrames","Plots","Test"]
```
